### ISSUE TITLE
Can't select any characters

### ISSUE THREAD

**Issue by Wingless-Archangel** [risbi0/Elysian-Realm#2]
When I tried to select any character, There were no actions on Chrome and Brave latest version.

after opening the developer tools, I found the following error. I hope that this will help to solve this issue.

```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
script.js:1 Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at 694 (https://risbi0.github.io/Elysian-Realm/static/script.js:1:112329)
    at r (https://risbi0.github.io/Elysian-Realm/static/script.js:1:116317)
    at https://risbi0.github.io/Elysian-Realm/static/script.js:1:117211
    at https://risbi0.github.io/Elysian-Realm/static/script.js:1:117233
694 @ script.js:1
r @ script.js:1
(anonymous) @ script.js:1
(anonymous) @ script.js:1
serviceWorker.js?device=dt:1 Service Worker: Fetching...
(index):1 Service Worker Registered
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...
serviceWorker.js?device=dt:1 Service Worker: Fetching...

```

**Comment by risbi0** [comment]
What's the URL of the website when you had this error?

**Comment by Wingless-Archangel** [comment]
https://risbi0.github.io/Elysian-Realm

**Comment by risbi0** [comment]
Can you provide steps on how to reproduce the bug?

**Comment by Wingless-Archangel** [comment]
Noting fancy just load the website and try to select character. I couldn't select anyone at all.

**Comment by FawazTakahji** [comment]
I had this problem with an older version of firefox, updating to the latest version fixed this.
